version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    environment:

    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            cat importmap.json

            echo "Updating import map"
            curl -X PATCH -u $DEPLOYER_USERNAME:$DEPLOYER_PASSWORD $DEPLOYER_HOST/import-map.json\?env=$DEPLOYER_ENV --data "@importmap.json" -H "Accept: application/json" -H "Content-Type: application/json" --fail --insecure

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          context: deploy-context
          filters:
            branches:
              only: master
